web:
    image: shaneburkhart/plansource:dev
    ports:
        - "3000:3000"
    links:
        - pg
        - redis
        - mailcatcher
    volumes:
        - ../..:/app
    env_file:
        - ../../user.env

react_build:
    image: shaneburkhart/plansource:dev
    volumes:
        - ../..:/app
    command: "npm run watch"

pg:
    image: postgres:9.6.17
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=mydb
    volumes:
        - ../../data/pg:/var/lib/postgresql/data

redis:
    image: redis:3.2

mailcatcher:
    image: shaneburkhart/plansource:dev
    ports:
        - "1080:1080"
    command: "mailcatcher --foreground --http-ip=0.0.0.0 --smtp-ip=0.0.0.0"

