development:
    host: pg
    #host: localhost
    port: 5432
    username: postgres
    password: postgres
    adapter: postgresql
    encoding: unicode
    database: mydb
    pool: 5

production:
    host: pg
    port: 5432
    username: postgres
    password: postgres
    adapter: postgresql
    encoding: unicode
    database: mydb
    pool: 5
